import './globals.css'
import { Montserrat } from 'next/font/google'
import { TelegramBotComponent } from '@/components/TelegramBotComponent'

const roboto = Montserrat({})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className + ' container'}>
        <TelegramBotComponent />
        {children}
      </body>
    </html>
  )
}
